import Navbar from "@/components/Navbar"
import { Poppins } from "next/font/google"
import { Providers } from "@/components/theme-provider";
import Footer from "@/components/Footer";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      {children}
      <Footer/>
    </div>
  )
}
