import Navbar from "@/components/Navbar"
import { Poppins } from "next/font/google"
import { Providers } from "@/components/theme-provider";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <Providers> 
      <body className="font-poppins">
        <Navbar/>
        {children}
        </body>
      </Providers>
    </html>
  )
}
